Set up project for bachelors thesis
s-heppner/python-semantic-matcher pull request #2
Opened 2024-05-27 10:52 UTC by dxvidnrt

This branch adds some features and bug fixes.
* Matches are searched recursive to find all fitting matches.
* Output list now isn't resetted anymore and shows all fitting matches.
* Add endpoint get_all_matches
* Change host to 0.0.0.0 to work with docker environment

2024-06-20 07:55 UTC, s-heppner requested changes
I think the biggest issue I see at the moment is the cross-dependency you introduced to the semantic_id_resolver. 
If possible at all, I would avoid calling that in as a dependency. 

If that doesn't work out, my suggestion is to create a completely new repository for the test framework, where you pull in both projects as dependency.

2024-06-21 11:06 UTC, dxvidnrt commented on semantic_matcher/service.py
> +        )
Yes, removed it

2024-06-21 11:16 UTC, dxvidnrt commented on config.ini.default
> +[RESOLVER]
If I understand you correctly, we add information to the semantic_id itself.
The current structure is: "SMS_ID"/semanticID/"ID".
So we could add the corresponding resolver endpoint: "Resolver_Endpoint"/"SMS_ID"/semanticID/"ID".

2024-06-26 07:03 UTC, s-heppner commented on config.ini.default
> +[RESOLVER]
Nevermind, we do need to specify the resolver on the Semantic Matching Service level.

2024-06-26 07:04 UTC, s-heppner commented on semantic_matcher/service.py
> +
Should be removed as well

2024-06-27 12:26 UTC, dxvidnrt commented on requirements.txt
> +git+https://github.com/dxvidnrt/semantic_id_resolver
Dependency removed

2024-06-27 12:26 UTC, dxvidnrt commented on semantic_matcher/service.py
> +        return None
Dependency resolved, implemented as dict

2024-06-27 12:26 UTC, dxvidnrt commented on semantic_matcher/service.py
> +
Removed

2024-06-27 13:08 UTC, s-heppner requested changes
Except for this minor thing, it looks good to me.

2024-06-27 13:08 UTC, s-heppner commented on requirements.txt
> +requests>=2.31.0
Can you reintroduce the empty newline at the end of the file?

2024-06-27 13:14 UTC, s-heppner commented
I took the liberty to improve your PR title and message, so that we can use it as commit message, when we squash and merge.

2024-06-28 06:44 UTC, s-heppner approved these changes
LGTM now

2024-06-28 06:45 UTC, merged